

local S = lib_materials.intllib


	local mgparams = minetest.get_mapgen_params()
	local mg_seed = mgparams.seed

	local __ = {name = "air",param2 = 0,prob = 0}
	local aa = {name = "air",param2 = 0,prob = 254, force_place = true}
	local WW = {name = "lib_materials:liquid_water_river_source", param2 = 0, prob = 254, force_place = true}



	le_temp_schem = {
		size = {x = 13, y = 17, z = 13},
		data = {
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, aa, aa, aa, aa, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			__, __, __, __, __, __, __, __, __, __, __, __, __,				--1
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,

			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			__, __, __, __, __, __, __, __, __, __, __, __, __,				--2
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,

			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,

			__, __, __, WW, WW, WW, WW, WW, WW, WW, __, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,

			__, __, __, WW, WW, WW, WW, WW, WW, WW, __, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,

			__, __, __, WW, WW, WW, WW, WW, WW, WW, __, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,

			__, __, __, WW, WW, WW, WW, WW, WW, WW, __, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,

			__, __, __, WW, WW, WW, WW, WW, WW, WW, __, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,

			__, __, __, WW, WW, WW, WW, WW, WW, WW, __, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,

			__, __, __, WW, WW, WW, WW, WW, WW, WW, __, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,

			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,

			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,

			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, aa, aa, aa, aa, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __, __, __
		},
		yslice_prob = {
			{ypos = 0,prob = 254},
			{ypos = 1,prob = 254},
			{ypos = 2,prob = 254},
			{ypos = 3,prob = 254},
			{ypos = 4,prob = 254},
			{ypos = 5,prob = 254},
			{ypos = 6,prob = 254},
			{ypos = 7,prob = 254},
			{ypos = 8,prob = 254},
			{ypos = 9,prob = 254},
			{ypos = 10,prob = 254},
			{ypos = 11,prob = 254},
			{ypos = 12,prob = 254},
			{ypos = 13,prob = 254},
			{ypos = 14,prob = 254},
			{ypos = 15,prob = 254},
			{ypos = 16,prob = 254}
		}
	}
	minetest.register_decoration({
	   deco_type = "schematic",
	   place_on = {"group:soil", "group:dirt", "group:sand"},
	   sidelen = 1,
	   noise_params = {
	      offset = 100.0,
	      scale = -20000.0,
	      spread = {x = 256, y = 256, z = 256},
	      seed = 5934,
	      octaves = 1,
	      persist = 0.5,
	      lacunarity = 2.22,
	      flags = "defaults, noeased, absvalue"
	   },
	   y_max = 3,
	   y_min = 1,
	   flags = "force_placement, place_center_x, place_center_y, place_center_z",
	   schematic = le_temp_schem,
	})



	le_temp_schem = {
		size = {x = 11, y = 13, z = 11},
		data = {
			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __,
			__, __, aa, aa, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,

			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,

			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,

			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, WW, WW, WW, WW, WW, __, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,

			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, WW, WW, WW, __, __, __, __,
			__, __, __, WW, WW, WW, WW, WW, __, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,

			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, WW, WW, WW, __, __, __, __,
			__, __, __, WW, WW, WW, WW, WW, __, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,

			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, WW, WW, WW, __, __, __, __,
			__, __, __, WW, WW, WW, WW, WW, __, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,

			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, WW, WW, WW, WW, WW, __, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,

			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,

			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,

			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __, __, __,
			__, __, aa, aa, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa, aa, aa,
		},
		yslice_prob = {
			{ypos = 0,prob = 254},
			{ypos = 1,prob = 254},
			{ypos = 2,prob = 254},
			{ypos = 3,prob = 254},
			{ypos = 4,prob = 254},
			{ypos = 5,prob = 254},
			{ypos = 6,prob = 254},
			{ypos = 7,prob = 254},
			{ypos = 8,prob = 254},
			{ypos = 9,prob = 254},
			{ypos = 10,prob = 254},
			{ypos = 11,prob = 254},
			{ypos = 12,prob = 254}
		}
	}
	minetest.register_decoration({
	   deco_type = "schematic",
	   place_on = {"group:soil", "group:dirt", "group:sand"},
	   sidelen = 1,
	   noise_params = {
	      offset = 100.0,
	      scale = -20000.0,
	      spread = {x = 256, y = 256, z = 256},
	      seed = 5934,
	      octaves = 1,
	      persist = 0.5,
	      lacunarity = 2.22,
	      flags = "defaults, noeased, absvalue"
	   },
	   y_max = 6,
	   y_min = 3,
	   flags = "force_placement, place_center_x, place_center_y, place_center_z",
	   schematic = le_temp_schem,
	})


	le_temp_schem = {
		size = {x = 9, y = 11, z = 9},
		data = {
			__, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __,
			__, __, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,

			__, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __,
			__, __, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,

			__, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __,
			__, __, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,

			__, __, __, __, __, __, __, __, __,
			__, __, __, WW, WW, WW, __, __, __,
			__, __, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,

			__, __, __, __, __, __, __, __, __,
			__, __, __, WW, WW, WW, __, __, __,
			__, __, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,

			__, __, __, __, __, __, __, __, __,
			__, __, __, WW, WW, WW, __, __, __,
			__, __, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,

			__, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __,
			__, __, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,

			__, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __,
			__, __, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, __, __,
			__, __, WW, WW, WW, WW, WW, __, __,
			__, __, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,

			__, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __,
			__, __, __, __, __, __, __, __, __,
			__, __, aa, aa, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa, aa, aa
		},
		yslice_prob = {
			{ypos = 0,prob = 254},
			{ypos = 1,prob = 254},
			{ypos = 2,prob = 254},
			{ypos = 3,prob = 254},
			{ypos = 4,prob = 254},
			{ypos = 5,prob = 254},
			{ypos = 6,prob = 254},
			{ypos = 7,prob = 254},
			{ypos = 8,prob = 254},
			{ypos = 9,prob = 254},
			{ypos = 10,prob = 254}
		}
	}
	minetest.register_decoration({
	   deco_type = "schematic",
	   place_on = {"group:soil", "group:dirt", "group:sand"},
	   sidelen = 1,
	   noise_params = {
	      offset = 100.0,
	      scale = -20000.0,
	      spread = {x = 256, y = 256, z = 256},
	      seed = 5934,
	      octaves = 1,
	      persist = 0.5,
	      lacunarity = 2.22,
	      flags = "defaults, noeased, absvalue"
	   },
	   y_max = 10,
	   y_min = 6,
	   flags = "force_placement, place_center_x, place_center_y, place_center_z",
	   schematic = le_temp_schem,
	})


	le_temp_schem = {
		size = {x = 7, y = 11, z = 7},
		data = {
			__, __, __, __, __, __, __,
			__, __, __, __, __, __, __,
			__, __, __, __, __, __, __,
			__, __, __, __, __, __, __,
			__, __, aa, aa, aa, __, __,
			__, __, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa,

			__, __, __, __, __, __, __,
			__, __, __, __, __, __, __,
			__, __, WW, WW, WW, __, __,
			__, __, WW, WW, WW, __, __,
			__, __, WW, WW, WW, __, __,
			__, __, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa,

			__, __, __, __, __, __, __,
			__, __, __, __, __, __, __,
			__, __, WW, WW, WW, __, __,
			__, __, WW, WW, WW, __, __,
			__, __, WW, WW, WW, __, __,
			__, __, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa,

			__, __, __, __, __, __, __,
			__, __, __, WW, __, __, __,
			__, __, WW, WW, WW, __, __,
			__, __, WW, WW, WW, __, __,
			__, __, WW, WW, WW, __, __,
			__, __, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa,

			__, __, __, __, __, __, __,
			__, __, __, __, __, __, __,
			__, __, WW, WW, WW, __, __,
			__, __, WW, WW, WW, __, __,
			__, __, WW, WW, WW, __, __,
			__, __, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa,

			__, __, __, __, __, __, __,
			__, __, __, __, __, __, __,
			__, __, WW, WW, WW, __, __,
			__, __, WW, WW, WW, __, __,
			__, __, WW, WW, WW, __, __,
			__, __, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa,

			__, __, __, __, __, __, __,
			__, __, __, __, __, __, __,
			__, __, __, __, __, __, __,
			__, __, __, __, __, __, __,
			__, __, aa, aa, aa, __, __,
			__, __, aa, aa, aa, __, __,
			__, aa, aa, aa, aa, aa, __,
			aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa, aa, aa,
		},
		yslice_prob = {
			{ypos = 0,prob = 254},
			{ypos = 1,prob = 254},
			{ypos = 2,prob = 254},
			{ypos = 3,prob = 254},
			{ypos = 4,prob = 254},
			{ypos = 5,prob = 254},
			{ypos = 6,prob = 254},
			{ypos = 7,prob = 254},
			{ypos = 8,prob = 254},
			{ypos = 9,prob = 254},
			{ypos = 10,prob = 254}
		}
	}
	minetest.register_decoration({
	   deco_type = "schematic",
	   place_on = {"group:soil", "group:dirt", "group:sand"},
	   sidelen = 1,
	   noise_params = {
	      offset = 100.0,
	      scale = -20000.0,
	      spread = {x = 256, y = 256, z = 256},
	      seed = 5934,
	      octaves = 1,
	      persist = 0.5,
	      lacunarity = 2.22,
	      flags = "defaults, noeased, absvalue"
	   },
	   y_max = 15,
	   y_min = 10,
	   flags = "force_placement, place_center_x, place_center_y, place_center_z",
	   schematic = le_temp_schem,
	})



	le_temp_schem = {
		size = {x = 5, y = 9, z = 5},
		data = {
			__, __, __, __, __,
			__, __, __, __, __,
			__, __, __, __, __,
			__, __, __, __, __,
			__, aa, aa, aa, __,
			aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa,

			__, __, __, __, __,
			__, WW, WW, __, __,
			__, WW, WW, WW, __,
			__, WW, WW, WW, __,
			__, aa, aa, aa, __,
			aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa,

			__, __, __, __, __,
			__, WW, WW, WW, __,
			__, WW, WW, WW, __,
			__, WW, WW, WW, __,
			__, aa, aa, aa, __,
			aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa,

			__, __, __, __, __,
			__, __, WW, WW, __,
			__, WW, WW, WW, __,
			__, WW, WW, WW, __,
			__, aa, aa, aa, __,
			aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa,

			__, __, __, __, __,
			__, __, __, __, __,
			__, __, __, __, __,
			__, __, __, __, __,
			__, aa, aa, aa, __,
			aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa,
			aa, aa, aa, aa, aa
		},
		yslice_prob = {
			{ypos = 0,prob = 254},
			{ypos = 1,prob = 254},
			{ypos = 2,prob = 254},
			{ypos = 3,prob = 254},
			{ypos = 4,prob = 254},
			{ypos = 5,prob = 254},
			{ypos = 6,prob = 254},
			{ypos = 7,prob = 254},
			{ypos = 8,prob = 254}
		}
	}
	minetest.register_decoration({
	   deco_type = "schematic",
	   place_on = {"group:soil", "group:dirt", "group:sand"},
	   sidelen = 1,
	   noise_params = {
	      offset = 100.0,
	      scale = -20000.0,
	      spread = {x = 256, y = 256, z = 256},
	      seed = 5934,
	      octaves = 1,
	      persist = 0.5,
	      lacunarity = 2.22,
	      flags = "defaults, noeased, absvalue"
	   },
	   y_max = 30,
	   y_min = 15,
	   flags = "force_placement, place_center_x, place_center_y, place_center_z",
	   schematic = le_temp_schem,
	})



	le_temp_schem = {
		size = {x = 3, y = 7, z = 3},
		data = {
			__, __, __,
			__, __, __,
			__, __, __,
			__, __, __,
			__, aa, __,
			aa, aa, aa,
			aa, aa, aa,

			__, __, __,
			__, WW, __,
			__, WW, __,
			__, aa, __,
			__, aa, __,
			aa, aa, aa,
			aa, aa, aa,

			__, __, __,
			__, __, __,
			__, __, __,
			__, __, __,
			__, aa, __,
			aa, aa, aa,
			aa, aa, aa
		},
		yslice_prob = {
			{ypos = 0,prob = 254},
			{ypos = 1,prob = 254},
			{ypos = 2,prob = 254},
			{ypos = 3,prob = 254},
			{ypos = 4,prob = 254},
			{ypos = 5,prob = 254},
			{ypos = 6,prob = 254}
		}
	}
	minetest.register_decoration({
	   deco_type = "schematic",
	   place_on = {"group:soil", "group:dirt", "group:sand"},
	   sidelen = 1,
	   noise_params = {
	      offset = 100.0,
	      scale = -20000.0,
	      spread = {x = 256, y = 256, z = 256},
	      seed = 5934,
	      octaves = 1,
	      persist = 0.5,
	      lacunarity = 2.22,
	      flags = "defaults, noeased, absvalue"
	   },
	   y_max = 60,
	   y_min = 30,
	   flags = "force_placement, place_center_x, place_center_y, place_center_z",
	   schematic = le_temp_schem,
	})



--[[
	minetest.register_decoration({
	   deco_type = "simple",
	   place_on = {"group:soil"},
	   sidelen = 16,
	   noise_params = {
	      offset = 100.0,
	      scale = -2000.0,
	      spread = {x = 256, y = 256, z = 256},
	      seed = mg_seed,
	      octaves = 1,
	      persist = 0.5,
	      lacunarity = 2.22,
	      flags = "defaults, noeased, absvalue"
	   },
	   y_max = 10,
	   y_min = 0,
	   place_offset_y = -1,
	   flags = "force_placement",
	   decoration = "air",
	})
	minetest.register_decoration({
	   deco_type = "simple",
	   place_on = {"group:soil"},
	   sidelen = 8,
	   noise_params = {
	      offset = 100.0,
	      scale = -4000.0,
	      spread = {x = 256, y = 256, z = 256},
	      seed = mg_seed,
	      octaves = 1,
	      persist = 0.5,
	      lacunarity = 2.22,
	      flags = "defaults, noeased, absvalue"
	   },
	   y_max = 20,
	   y_min = 10,
	   place_offset_y = -1,
	   flags = "force_placement",
	   decoration = "air",
	})

	minetest.register_decoration({
	   deco_type = "simple",
	   place_on = {"group:soil"},
	   sidelen = 4,
	   noise_params = {
	      offset = 100.0,
	      scale = -8000.0,
	      spread = {x = 256, y = 256, z = 256},
	      seed = mg_seed,
	      octaves = 1,
	      persist = 0.5,
	      lacunarity = 2.22,
	      flags = "defaults, noeased, absvalue"
	   },
	   y_max = 50,
	   y_min = 20,
	   place_offset_y = -1,
	   flags = "force_placement",
	   decoration = "air",
	})

	minetest.register_decoration({
	   deco_type = "simple",
	   place_on = {"group:soil"},
	   sidelen = 2,
	   noise_params = {
	      offset = 100.0,
	      scale = -16000.0,
	      spread = {x = 256, y = 256, z = 256},
	      seed = mg_seed,
	      octaves = 1,
	      persist = 0.5,
	      lacunarity = 2.48,
	      flags = "defaults, noeased, absvalue"
	   },
	   y_max = 60,
	   y_min = 50,
	   place_offset_y = -1,
	   flags = "force_placement",
	   decoration = "air",
	})
--]]


